name: tests

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit Tests
        run: |
          make test

      - name: Lex
        run: |
          make lex

      - name: Parse
        run: |
          make parse

      - name: Run testdata
        run: |
          make testdata

      - name: Codecov
        uses: codecov/codecov-action@v3
