name: tests

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lex
        run: |
          make lex

      - name: Parse
        run: |
          make parse

      - name: Unit Tests
        run: |
          make test

      - name: Run testdata
        run: |
          make testdata
